/** Everything that has an illustration: peripherals, the computer, its internal parts, the connection. */
export type Kind =
  | "computer"
  | "monitor"
  | "keyboard"
  | "mouse"
  | "webcam"
  | "audio"
  | "microphone"
  | "gamepad"
  | "storage"
  | "printer"
  | "hub"
  | "wireless"
  | "phone"
  | "securitykey"
  | "generic"
  // inside the computer
  | "board"
  | "cpu"
  | "ram"
  | "gpu"
  | "nvme"
  | "ssd"
  | "hdd"
  | "psu"
  | "nic"
  | "soundcard"
  // the connection to the internet
  | "router"
  | "internet";
